[project]
name = "aoc-2025"
version = "0.1.0"
description = "Advent of Code (AoC) 2025, Python implementation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.1",
    "shapely>=2.1.2",
    "z3-solver>=4.15.4.0",
]
